//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIFT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Gallery
    {
        [DisplayName("รหัสรูปสินค้า")]
        public int Gallery_ID { get; set; }
        [DisplayName("รหัสสินค้า")]
        public int P_ID { get; set; }
        [DisplayName("รูป")]
        public string Gallery_Name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
