//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIFT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        [DisplayName("รหัสสินค้า")]
        public int P_ID { get; set; }
        [DisplayName("ชื่อสินค้า")]
        public string P_name { get; set; }
        [DisplayName("ประเภทสินค้า")]
        public int Ca_ID { get; set; }
        [DisplayName("รูปสินค้า")]
        public string P_img { get; set; }
        [DisplayName("รูปสินค้า")]
        public string P_img_1 { get; set; }
        [DisplayName("รูปสินค้า")]
        public string P_img_2 { get; set; }
        [DisplayName("รูปสินค้า")]
        public string P_img_3 { get; set; }
        [DisplayName("ราคา")]
        public Nullable<decimal> P_price { get; set; }
        [DisplayName("สี")]
        public string P_colur { get; set; }
        [DisplayName("ไซต์")]
        public string P_size { get; set; }
        [DisplayName("เนื้อผ้า")]
        public string P_texture { get; set; }
        [DisplayName("ความยาว")]
        public string P_length { get; set; }
        [DisplayName("รอบอก/รอบเอว")]
        public string P_chest_waistline { get; set; }
        [DisplayName("จำนวนสินค้า")]
        public int P_amount { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }

    }
}
