//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIFT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SaleDetail
    {
        [DisplayName("เลขที่ใบชำระเงิน")]
        public int S_ID { get; set; }
        [DisplayName("รหัสสินค้า")]
        public int P_ID { get; set; }
        [DisplayName("จำนวน")]
        public int Sd_number { get; set; }
        [DisplayName("เลขที่ใบสั่งซื้อ")]
        public int Sale_ID { get; set; }
        [DisplayName("ราคา")]
        public int Pro_Price { get; set; }
        [DisplayName("ชื่อ")]
        public int U_ID { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
