//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIFT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }

        [DisplayName("เลขที่ใบสั่งซื้อ")]
        public int S_ID { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("วันที่สั่งซื้อ")]
        public System.DateTime S_date { get; set; }
        [DisplayName("ชื่อลูกค้า")]
        public int U_ID { get; set; }
        [DisplayName("ที่อยู่จัดส่ง")]
        public string S_add { get; set; }
        [DisplayName("วิธีการจัดส่ง")]
        public int D_ID { get; set; }
        [DisplayName("ราคารวม")]
        public int S_sum { get; set; }
        [DisplayName("ใบสลิป")]
        public string S_slip { get; set; }
        [DisplayName("สถานะ")]
        public int Staus_ID { get; set; }
        [DisplayName("หมายเลขพัสดุ")]
        public string S_packagenumber { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual User User { get; set; }
        public virtual Stau Stau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
